#!/usr/bin/env php-cgi
<?php
# Local Variables:
# mode: php
# End:
header('Content-type: text/plain');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');

$root=$_SERVER["KPHOME"];

$curtags=array_values(array_filter(explode("/", $_SERVER["PATH_INFO"])));

$tags = array();

$dir = $root."/exe";
if($dh = opendir($dir)) {
  while (($file = readdir($dh)) !== false) {
    if($file == ".") continue;
    if($file == "..") continue;
    $fn = $dir."/".$file."/tags";
    if(!file_exists($fn)) {
      continue;
    }
    $flag=0;
    $jobtags=file_get_contents($fn);
    $u = explode("\n", $jobtags);

    # if not toplevel (no tags). only select tags from jobs containing the current tags
    $flag=1;
    if(count($curtags)) {
      foreach ($curtags as $key => $tag) {
	if(strlen($tag) > 0) {
	  if(!in_array($tag,$u)) {
	    $flag = 0;
	  }
	}
      }
      if($flag == 0) continue;
    }
    foreach ($u as $key => $tag) {
      if(strlen($tag) > 0) {
	$tags[$tag] = 1;
      }
    }
  }
  closedir($dh);
}

foreach ($tags as $key => $tag) {
  print "$key\n";
}
?>
